[2023-12-04T16:52:02.735+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_local_to_gcs_to_bigquery.transforms_data.transform_raw_data manual__2023-12-04T16:51:57.498952+00:00 [queued]>
[2023-12-04T16:52:02.753+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_local_to_gcs_to_bigquery.transforms_data.transform_raw_data manual__2023-12-04T16:51:57.498952+00:00 [queued]>
[2023-12-04T16:52:02.753+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-04T16:52:02.775+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transforms_data.transform_raw_data> on 2023-12-04 16:51:57.498952+00:00
[2023-12-04T16:52:02.786+0000] {standard_task_runner.py:57} INFO - Started process 79 to run task
[2023-12-04T16:52:02.792+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_local_to_gcs_to_bigquery', 'transforms_data.transform_raw_data', 'manual__2023-12-04T16:51:57.498952+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/etl_gcs_to_bq.py', '--cfg-path', '/tmp/tmp00d94adv']
[2023-12-04T16:52:02.796+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask transforms_data.transform_raw_data
[2023-12-04T16:52:02.866+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_local_to_gcs_to_bigquery.transforms_data.transform_raw_data manual__2023-12-04T16:51:57.498952+00:00 [running]> on host e9e41562f3b7
[2023-12-04T16:52:02.981+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_local_to_gcs_to_bigquery' AIRFLOW_CTX_TASK_ID='transforms_data.transform_raw_data' AIRFLOW_CTX_EXECUTION_DATE='2023-12-04T16:51:57.498952+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-04T16:51:57.498952+00:00'
[2023-12-04T16:52:04.908+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_gcs_to_bq.py", line 72, in transform
    save = result_df.to_parquet(f"{path_to_transform_dataset}/{dataset_transform_file}", index=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 2889, in to_parquet
    return to_parquet(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 411, in to_parquet
    impl.write(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 161, in write
    path_or_handle, handles, kwargs["filesystem"] = _get_path_or_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 110, in _get_path_or_handle
    handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 737, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 600, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/opt/***/dataset/transform'
[2023-12-04T16:52:04.927+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_local_to_gcs_to_bigquery, task_id=transforms_data.transform_raw_data, execution_date=20231204T165157, start_date=20231204T165202, end_date=20231204T165204
[2023-12-04T16:52:04.949+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task transforms_data.transform_raw_data (Cannot save file into a non-existent directory: '/opt/***/dataset/transform'; 79)
[2023-12-04T16:52:04.981+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-04T16:52:05.032+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
