[2023-12-13T17:06:36.937+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_local_to_gcs_to_bigquery_api.extract_transform_raw_data scheduled__2023-12-12T00:00:00+00:00 [queued]>
[2023-12-13T17:06:36.957+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_local_to_gcs_to_bigquery_api.extract_transform_raw_data scheduled__2023-12-12T00:00:00+00:00 [queued]>
[2023-12-13T17:06:36.962+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-13T17:06:37.032+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract_transform_raw_data> on 2023-12-12 00:00:00+00:00
[2023-12-13T17:06:37.050+0000] {standard_task_runner.py:57} INFO - Started process 62 to run task
[2023-12-13T17:06:37.065+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_local_to_gcs_to_bigquery_api', 'extract_transform_raw_data', 'scheduled__2023-12-12T00:00:00+00:00', '--job-id', '285', '--raw', '--subdir', 'DAGS_FOLDER/etl_gcs_to_bq_api.py', '--cfg-path', '/tmp/tmpz6gpo81u']
[2023-12-13T17:06:37.069+0000] {standard_task_runner.py:85} INFO - Job 285: Subtask extract_transform_raw_data
[2023-12-13T17:06:37.150+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_local_to_gcs_to_bigquery_api.extract_transform_raw_data scheduled__2023-12-12T00:00:00+00:00 [running]> on host c0a30b49a736
[2023-12-13T17:06:37.272+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_local_to_gcs_to_bigquery_api' AIRFLOW_CTX_TASK_ID='extract_transform_raw_data' AIRFLOW_CTX_EXECUTION_DATE='2023-12-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-12T00:00:00+00:00'
[2023-12-13T17:06:39.649+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_gcs_to_bq_api.py", line 39, in transform_api
    provinsi = data['data']['state']
KeyError: 'state'
[2023-12-13T17:06:39.702+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_local_to_gcs_to_bigquery_api, task_id=extract_transform_raw_data, execution_date=20231212T000000, start_date=20231213T170636, end_date=20231213T170639
[2023-12-13T17:06:39.790+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 285 for task extract_transform_raw_data ('state'; 62)
[2023-12-13T17:06:39.837+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-13T17:06:39.919+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
