[2023-12-07T16:27:59.573+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_local_to_gcs_to_bigquery.loads_raw_data.upload_raw_data_2014_to_gcs manual__2023-12-07T16:23:04.448993+00:00 [queued]>
[2023-12-07T16:27:59.615+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_local_to_gcs_to_bigquery.loads_raw_data.upload_raw_data_2014_to_gcs manual__2023-12-07T16:23:04.448993+00:00 [queued]>
[2023-12-07T16:27:59.616+0000] {taskinstance.py:1361} INFO - Starting attempt 3 of 3
[2023-12-07T16:27:59.655+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): loads_raw_data.upload_raw_data_2014_to_gcs> on 2023-12-07 16:23:04.448993+00:00
[2023-12-07T16:27:59.669+0000] {standard_task_runner.py:57} INFO - Started process 5539 to run task
[2023-12-07T16:27:59.683+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_local_to_gcs_to_bigquery', 'loads_raw_data.upload_raw_data_2014_to_gcs', 'manual__2023-12-07T16:23:04.448993+00:00', '--job-id', '158', '--raw', '--subdir', 'DAGS_FOLDER/etl_gcs_to_bq.py', '--cfg-path', '/tmp/tmpmubnvnc_']
[2023-12-07T16:27:59.689+0000] {standard_task_runner.py:85} INFO - Job 158: Subtask loads_raw_data.upload_raw_data_2014_to_gcs
[2023-12-07T16:27:59.783+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_local_to_gcs_to_bigquery.loads_raw_data.upload_raw_data_2014_to_gcs manual__2023-12-07T16:23:04.448993+00:00 [running]> on host f19d185ad9e6
[2023-12-07T16:27:59.982+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_local_to_gcs_to_bigquery' AIRFLOW_CTX_TASK_ID='loads_raw_data.upload_raw_data_2014_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2023-12-07T16:23:04.448993+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-07T16:23:04.448993+00:00'
[2023-12-07T16:27:59.989+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2023-12-07T16:27:59.994+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2023-12-07T16:28:00.002+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-12-07T16:28:00.005+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_gcs_to_bq.py", line 370, in upload_raw_2014_to_gcs
    upload_task.execute(context=kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/transfers/local_to_gcs.py", line 97, in execute
    raise FileNotFoundError(self.src)
FileNotFoundError: /opt/***/dataset/raw/Indeks-Standar-Pencemar-Udara-di-SPKU-Bulan-Januari-Tahun-2014.csv
[2023-12-07T16:28:00.035+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_local_to_gcs_to_bigquery, task_id=loads_raw_data.upload_raw_data_2014_to_gcs, execution_date=20231207T162304, start_date=20231207T162759, end_date=20231207T162800
[2023-12-07T16:28:00.062+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 158 for task loads_raw_data.upload_raw_data_2014_to_gcs (/opt/***/dataset/raw/Indeks-Standar-Pencemar-Udara-di-SPKU-Bulan-Januari-Tahun-2014.csv; 5539)
[2023-12-07T16:28:00.102+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-07T16:28:00.148+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
